### ISSUE TITLE
Problem with service registration

### ISSUE THREAD

**Issue by ChrisMagnuson** [Tervis-Tumbler/au-packages#1]
http://disq.us/p/1fyed9t

Please fix the path "kibana-$PackageVersion-windows\bin\kibana.bat" for service registration, actual installation folder is following the zip package name with '-x86' suffix that causes "Failed to start service kibana-service... The system cannot find the file specified"

**Comment by angryhussord** [comment]
2 months and we're still waiting on this fix to the 5.2.1 installer in Chocolatey.

After you install the chocolatey package you need to make some adjustments:

nssm.exe edit kibana-service

Path:
c:\ProgramData\chocolatey\lib\kibana\tools\kibana-5.2.1-windows-x86\bin\kibana.bat
Startup Directory:
c:\ProgramData\chocolatey\lib\kibana\tools\kibana-5.2.1-windows-x86\bin

Click "Edit Service" to fix the directory paths and close NSSM.

net start kibana-service

**Comment by ChrisMagnuson** [comment]
@angryhussord Sorry for the delay, hopefully you saw the comment on the chocolatey package's discuss thread. This has been fixed in 50a1e075b24a8ab39ed3a5233d4fedf194a58c9e
