### ISSUE TITLE
Update logstash choco package

### ISSUE THREAD

**Issue by davidobrien1985** [Tervis-Tumbler/au-packages#10]
Hi guys,

any plans to update the logstash choco package to the latest version 6.x?

**Comment by ChrisMagnuson** [comment]
@davidobrien1985  Sorry it has taken so long, there was some other broken packages that blocked the auto update process from working but this has been fixed and the current version of the logstash package was picked up by appveyor and submitted to chocolatey.org.

We should see the new version show up in a few days after it goes through moderation.

**Comment by ChrisMagnuson** [comment]
https://chocolatey.org/packages/logstash/6.2.4
