### ISSUE TITLE
Set kibana service to be Automatic and autostart it

### ISSUE THREAD

**Issue by angryhussord** [Tervis-Tumbler/au-packages#5]
In the spirit of Chocolatey, an apt-get style tool for package management and installation, I beg you to automatically set the startup type to automatic and then automatically start the service as well. The audience using Chocolatey doesn't need that choice. We want our software auto-installed and running without any hand edits or after-install configuration whenever possible.

**Comment by ChrisMagnuson** [comment]
@angryhussord Sorry it has taken so long to get back to you.

If you look at the documentation for the [rpm package](https://www.elastic.co/guide/en/kibana/current/rpm.html#install-rpm) and [deb package](https://www.elastic.co/guide/en/kibana/current/deb.html#install-deb) of Kibana from elastic search they both do not start automatically after Kibana has been installed but leave that as a additional step for someone to perform if they want it automatically started.

My general experience with Arch linux and others has been that many server style applications default to creating the service but starting it or not setting it to start automatically.

Given that Elastic.co isn't currently starting the service via their other distribution means and it doesn't feel like it is a hard and fast rule or expectation that installed servers should automatically start I think it is better to have the kibana package configure a service but leave it set to manual and not automatic.

**Comment by ChrisMagnuson** [comment]
As a counter example the [maria db chocolatey package](https://chocolatey.org/packages/mariadb) does start the MySQL service after the package is installed.

**Comment by ChrisMagnuson** [comment]
Closing as there seems to be a precedent for the current behavior.
