### ISSUE TITLE
Incorrect Service Install Path for Blackbox Exporter

### ISSUE THREAD

**Issue by andrewmostello** [Tervis-Tumbler/au-packages#8]
Unfortunately the current version of the package has an error.

The path used on line 34...

`Start-ChocolateyProcessAsAdmin "install $ServiceName $(Join-Path $env:chocolateyPackageFolder "tools\prometheus-$PackageVersion.windows-amd64\prometheus.exe")" nssm`

...is not where the exe is located. It's found instead at 

`tools\blackbox_exporter-$PackageVersion.windows-amd64\blackbox_exporter.exe`

I'm not sure if this is something that would change again in the future, but I have a fix that should take care of this and any future changes.

**Comment by ChrisMagnuson** [comment]
Running `choco upgrade prometheus-blackbox-exporter --version 0.5.0.20170621 -y` I got the following:

```
C:\ProgramData\chocolatey\lib\prometheus-blackbox-exporter\tools
ERROR: Cannot process argument transformation on parameter 'fileFullPath'. Cannot convert value to type System.String.
The upgrade of prometheus-blackbox-exporter was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\prometheus-blackbox-exporter\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - prometheus-blackbox-exporter (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\prometheus-blackbox-exp
orter\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by andrewmostello** [comment]
Hmm, what did the log report? I ran the install process on the chocolatey test vagrant box but I didn't run through an upgrade.

**Comment by andrewmostello** [comment]
It might be the case that during `$File = Get-ChildItem -File -Path $env:ChocolateyInstall\lib\$packageName\tools\ -Filter *.tar` it found multiple .tar files. That would account for the conversion to string error, since Get-ChildItem would return an array.

**Comment by ChrisMagnuson** [comment]
Uninstalled and reinstalled and it worked without errors, hopefully that was just an issue on my side. Thanks for sending the pull request!
